apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: gcp-meetup-global
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcp-meetup-global
    spec:
      containers:
      - image: lkysow/gcp-meetup
        name: gcp-meetup-global
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        env:
        - name: CONFIG
          valueFrom:
            configMapKeyRef:
              name: gcp-meetup
              key: date
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: gcp-secret
              key: password
        - name: USELESS
          value: what