apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: gcp-meetup-global
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcp-meetup-global
    spec:
      containers:
      - image: lkysow/gcp-meetup
        name: gcp-meetup-global
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName